name: opencv-gui-env
channels:
  - defaults
dependencies:
  - python==3.9.0
  - pip:
    - opencv-python==4.6.0.66
    - opencv-contrib-python==4.6.0.66
    - numpy==1.25.0
    - qtpy>=2.0.0
    - pyside6